"""Tech changes (placeholder migration)

Revision ID: a1b2c3d4e5f6
Revises: 827b6ce0d8b6
Create Date: 2026-06-02 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '827b6ce0d8b6'
branch_labels = None
depends_on = None


def upgrade():
    # Placeholder: no schema changes detected. If you ran `alembic revision --autogenerate`,
    # replace this file's body with the autogenerated operations.
    pass


def downgrade():
    # Placeholder downgrade
    pass
